# RaceCAN Digital Kit
# Simulator configuration values

NODE_ID = 1

# Timing
SIMULATION_DELAY_SECONDS = 0.5

# Warning thresholds
VOLTAGE_WARNING_THRESHOLD = 11.0
TEMPERATURE_WARNING_THRESHOLD = 50.0
CURRENT_WARNING_THRESHOLD = 12.0

# Fault thresholds
UNDERVOLTAGE_FAULT_THRESHOLD = 10.5
OVERTEMPERATURE_FAULT_THRESHOLD = 60.0
OVERCURRENT_FAULT_THRESHOLD = 15.0

# Sensor limits
MIN_SENSOR_PERCENT = 0.0
MAX_SENSOR_PERCENT = 100.0

# CAN IDs
CAN_ID_HEARTBEAT = "0x100"
CAN_ID_VOLTAGE = "0x101"
CAN_ID_TEMPERATURE = "0x102"
CAN_ID_DRIVER_INPUTS = "0x103"
CAN_ID_CURRENT = "0x104"
CAN_ID_FAULTS = "0x105"
