#!/usr/bin/env python3
"""
RaceCAN Test Harness (test_harness.py)

Validates RaceCAN firmware behavior against the Day 16 test matrix by:
1. Injecting synthetic sensor stimuli (voltage, temperature, current, throttle, brake)
2. Packing CAN message payloads using the Day 15 protocol spec
3. Verifying message contents, timing, and state transitions
4. Logging results and detecting anomalies

Usage:
    python3 test_harness.py [test_id | all]
    
Example:
    python3 test_harness.py B.1        # Run voltage nominal test
    python3 test_harness.py all         # Run entire test matrix
    python3 test_harness.py B --verbose # Run all Section B tests with detailed output

Assumptions:
- Firmware is running in Arduino simulator or on target hardware via serial/CAN bridge
- Sensor values are injected via Python simulation (not via real hardware)
- CAN messages are captured via simulated bus or CAN interface
- Timestamps are generated by test harness (not recovered from hardware timing)
"""

import struct
import sys
from datetime import datetime
from collections import defaultdict
from typing import Dict, List, Tuple, Optional


class RaceCANMessage:
    """Represents a single CAN frame with payload and metadata."""
    
    def __init__(self, msg_id: int, dlc: int, data: bytes, timestamp_ms: float = 0.0):
        self.id = msg_id
        self.dlc = dlc
        self.data = data  # bytes, length dlc
        self.timestamp_ms = timestamp_ms
    
    def __repr__(self):
        data_hex = ' '.join(f'{b:02X}' for b in self.data)
        return f"ID=0x{self.id:03X} DLC={self.dlc} Data=[{data_hex}] T={self.timestamp_ms:.1f}ms"
    
    def get_field_u8(self, byte_offset: int) -> int:
        """Extract an unsigned 8-bit field."""
        return self.data[byte_offset]
    
    def get_field_u16_le(self, byte_offset: int) -> int:
        """Extract an unsigned 16-bit little-endian field."""
        low = self.data[byte_offset]
        high = self.data[byte_offset + 1]
        return low | (high << 8)
    
    def get_field_i16_le(self, byte_offset: int) -> int:
        """Extract a signed 16-bit little-endian field."""
        val = self.get_field_u16_le(byte_offset)
        if val >= 0x8000:
            val -= 0x10000
        return val


class RaceCANSimulator:
    """
    Simulates RaceCAN firmware behavior by maintaining internal state
    and generating CAN messages according to the Day 15 protocol spec.
    """
    
    def __init__(self):
        self.voltage = 12.0  # volts
        self.temperature = 25.0  # degrees C
        self.throttle = 0.0  # percent (0–100)
        self.brake = 0.0  # percent (0–100)
        self.current = 0.0  # amps
        self.uptime_sec = 0  # seconds
        self.external_fault = 0  # binary
        
        # Sensor range fault detection (must match firmware calibration)
        self.throttle_raw_min = 50
        self.throttle_raw_max = 950
        self.brake_raw_min = 60
        self.brake_raw_max = 980
        
        # Message history
        self.messages = []
        self.current_time_ms = 0.0
        
        # Configuration
        self.heartbeat_interval_ms = 500
        self.data_interval_ms = 100
        self.last_heartbeat_ms = 0.0
        self.last_data_ms = 0.0
    
    def set_sensor_values(self, voltage=None, temperature=None, throttle=None,
                         brake=None, current=None, external_fault=None):
        """Update sensor state."""
        if voltage is not None:
            self.voltage = voltage
        if temperature is not None:
            self.temperature = temperature
        if throttle is not None:
            self.throttle = min(100.0, max(0.0, throttle))
        if brake is not None:
            self.brake = min(100.0, max(0.0, brake))
        if current is not None:
            self.current = current
        if external_fault is not None:
            self.external_fault = external_fault
    
    def compute_sensor_range_fault(self) -> int:
        """Check if throttle or brake are out of calibrated range."""
        # Simulate ADC conversion: 0–100% maps to 0–1023 raw
        throttle_raw = int((self.throttle / 100.0) * 1023)
        brake_raw = int((self.brake / 100.0) * 1023)
        
        if (throttle_raw < self.throttle_raw_min or throttle_raw > self.throttle_raw_max or
            brake_raw < self.brake_raw_min or brake_raw > self.brake_raw_max):
            return 1
        return 0
    
    def compute_state_code(self) -> int:
        """Determine state code based on fault conditions."""
        # Critical thresholds
        if (self.voltage < 10.5 or self.temperature > 60.0 or 
            abs(self.current) > 15.0):
            return 2  # critical
        # Warning thresholds
        if (self.voltage < 11.0 or self.temperature > 50.0 or 
            abs(self.current) > 12.0 or self.compute_sensor_range_fault()):
            return 1  # warning
        return 0  # normal
    
    def pack_heartbeat(self) -> RaceCANMessage:
        """Pack 0x100 heartbeat message."""
        state_code = self.compute_state_code()
        data = bytearray(8)
        data[0] = 0x01  # alive flag
        data[1] = state_code
        data[2] = self.uptime_sec & 0xFF
        data[3] = (self.uptime_sec >> 8) & 0xFF
        # [4:7] reserved
        return RaceCANMessage(0x100, 8, bytes(data), self.current_time_ms)
    
    def pack_voltage(self) -> RaceCANMessage:
        """Pack 0x101 voltage telemetry message."""
        v_int = int(self.voltage * 100)
        v_warn = 1 if self.voltage < 11.0 else 0
        v_crit = 1 if self.voltage < 10.5 else 0
        
        data = bytearray(8)
        data[0] = v_int & 0xFF
        data[1] = (v_int >> 8) & 0xFF
        data[2] = v_warn
        data[3] = v_crit
        # [4:7] reserved
        return RaceCANMessage(0x101, 8, bytes(data), self.current_time_ms)
    
    def pack_temperature(self) -> RaceCANMessage:
        """Pack 0x102 temperature telemetry message."""
        t_int = int(self.temperature * 100)
        t_warn = 1 if self.temperature > 50.0 else 0
        t_crit = 1 if self.temperature > 60.0 else 0
        
        data = bytearray(8)
        data[0] = t_int & 0xFF
        data[1] = (t_int >> 8) & 0xFF
        data[2] = t_warn
        data[3] = t_crit
        # [4:7] reserved
        return RaceCANMessage(0x102, 8, bytes(data), self.current_time_ms)
    
    def pack_driver_inputs(self) -> RaceCANMessage:
        """Pack 0x103 driver inputs message."""
        throttle_int = int(self.throttle * 100)
        brake_int = int(self.brake * 100)
        range_fault = self.compute_sensor_range_fault()
        
        data = bytearray(8)
        data[0] = throttle_int & 0xFF
        data[1] = (throttle_int >> 8) & 0xFF
        data[2] = brake_int & 0xFF
        data[3] = (brake_int >> 8) & 0xFF
        data[4] = range_fault
        # [5:7] reserved
        return RaceCANMessage(0x103, 8, bytes(data), self.current_time_ms)
    
    def pack_current(self) -> RaceCANMessage:
        """Pack 0x104 current telemetry message."""
        i_int = int(self.current * 100)
        i_warn = 1 if abs(self.current) > 12.0 else 0
        i_crit = 1 if abs(self.current) > 15.0 else 0
        
        # Handle signed 16-bit
        if i_int < 0:
            i_int = (1 << 16) + i_int
        
        data = bytearray(8)
        data[0] = i_int & 0xFF
        data[1] = (i_int >> 8) & 0xFF
        data[2] = i_warn
        data[3] = i_crit
        # [4:7] reserved
        return RaceCANMessage(0x104, 8, bytes(data), self.current_time_ms)
    
    def pack_fault_summary(self) -> RaceCANMessage:
        """Pack 0x105 fault summary message."""
        range_fault = self.compute_sensor_range_fault()
        
        data = bytearray(8)
        data[0] = 1 if self.voltage < 11.0 else 0
        data[1] = 1 if self.voltage < 10.5 else 0
        data[2] = 1 if self.temperature > 50.0 else 0
        data[3] = 1 if self.temperature > 60.0 else 0
        data[4] = 1 if abs(self.current) > 12.0 else 0
        data[5] = 1 if abs(self.current) > 15.0 else 0
        data[6] = range_fault
        data[7] = self.external_fault
        return RaceCANMessage(0x105, 8, bytes(data), self.current_time_ms)
    
    def step(self, delta_ms: float):
        """Advance time and generate CAN messages at appropriate intervals."""
        self.current_time_ms += delta_ms
        self.uptime_sec = int(self.current_time_ms / 1000.0)
        
        # Heartbeat every 500ms
        if self.current_time_ms - self.last_heartbeat_ms >= self.heartbeat_interval_ms:
            self.messages.append(self.pack_heartbeat())
            self.last_heartbeat_ms = self.current_time_ms
        
        # Data messages every 100ms
        if self.current_time_ms - self.last_data_ms >= self.data_interval_ms:
            self.messages.append(self.pack_voltage())
            self.messages.append(self.pack_temperature())
            self.messages.append(self.pack_driver_inputs())
            self.messages.append(self.pack_current())
            self.messages.append(self.pack_fault_summary())
            self.last_data_ms = self.current_time_ms


class TestCase:
    """Represents a single test case from the test matrix."""
    
    def __init__(self, test_id: str, category: str, description: str,
                 stimulus_sequence: List[Dict], duration_ms: float,
                 expected_conditions: List[Dict]):
        self.test_id = test_id
        self.category = category  # NS, BC, FI, TM, SM
        self.description = description
        self.stimulus_sequence = stimulus_sequence
        self.duration_ms = duration_ms
        self.expected_conditions = expected_conditions
        self.result = None
        self.messages_captured = []
        self.errors = []
    
    def run(self, simulator: RaceCANSimulator, verbose: bool = False) -> bool:
        """Execute the test case."""
        if verbose:
            print(f"\nRunning {self.test_id}: {self.description}")
        
        # Clear message history
        simulator.messages = []
        simulator.current_time_ms = 0.0
        simulator.last_heartbeat_ms = 0.0
        simulator.last_data_ms = 0.0
        
        # Apply initial conditions (if any)
        current_stimulus_idx = 0
        for t_ms in range(0, int(self.duration_ms), 10):
            # Check if we need to update stimulus
            while (current_stimulus_idx < len(self.stimulus_sequence) and
                   t_ms >= self.stimulus_sequence[current_stimulus_idx].get('start_time_ms', 0)):
                stim = self.stimulus_sequence[current_stimulus_idx]
                simulator.set_sensor_values(**stim.get('values', {}))
                current_stimulus_idx += 1
            
            simulator.step(10)
        
        self.messages_captured = simulator.messages.copy()
        
        # Validate expected conditions
        self.result = self._validate()
        
        if verbose and self.errors:
            for error in self.errors:
                print(f"  ERROR: {error}")
        
        return len(self.errors) == 0
    
    def _validate(self) -> bool:
        """Check captured messages against expected conditions."""
        for condition in self.expected_conditions:
            msg_id = condition['msg_id']
            field = condition['field']
            expected = condition['expected']
            frame_range = condition.get('frame_range', (0, len(self.messages_captured)))
            
            # Find messages with matching ID in range
            matching_frames = [
                (idx, msg) for idx, msg in enumerate(self.messages_captured)
                if msg.id == msg_id and frame_range[0] <= idx < frame_range[1]
            ]
            
            if not matching_frames:
                self.errors.append(
                    f"No messages found with ID 0x{msg_id:03X} in frame range {frame_range}"
                )
                continue
            
            for frame_idx, msg in matching_frames:
                actual = self._extract_field(msg, field)
                if actual != expected:
                    self.errors.append(
                        f"Message 0x{msg_id:03X} Frame {frame_idx}, Field '{field}': "
                        f"expected {expected}, got {actual}"
                    )
        
        return len(self.errors) == 0
    
    def _extract_field(self, msg: RaceCANMessage, field: str) -> any:
        """Extract a named field from a message payload."""
        # Map field names to byte offsets and extraction methods
        field_map = {
            # Heartbeat (0x100)
            'alive': (lambda m: m.get_field_u8(0)),
            'state_code': (lambda m: m.get_field_u8(1)),
            'uptime': (lambda m: m.get_field_u16_le(2)),
            
            # Voltage (0x101)
            'voltage_raw': (lambda m: m.get_field_u16_le(0)),
            'voltage_v': (lambda m: m.get_field_u16_le(0) / 100.0),
            'voltage_warn': (lambda m: m.get_field_u8(2)),
            'voltage_crit': (lambda m: m.get_field_u8(3)),
            
            # Temperature (0x102)
            'temperature_raw': (lambda m: m.get_field_i16_le(0)),
            'temperature_c': (lambda m: m.get_field_i16_le(0) / 100.0),
            'temperature_warn': (lambda m: m.get_field_u8(2)),
            'temperature_crit': (lambda m: m.get_field_u8(3)),
            
            # Driver inputs (0x103)
            'throttle_raw': (lambda m: m.get_field_u16_le(0)),
            'throttle_pct': (lambda m: m.get_field_u16_le(0) / 100.0),
            'brake_raw': (lambda m: m.get_field_u16_le(2)),
            'brake_pct': (lambda m: m.get_field_u16_le(2) / 100.0),
            'range_fault': (lambda m: m.get_field_u8(4)),
            
            # Current (0x104)
            'current_raw': (lambda m: m.get_field_i16_le(0)),
            'current_a': (lambda m: m.get_field_i16_le(0) / 100.0),
            'current_warn': (lambda m: m.get_field_u8(2)),
            'current_crit': (lambda m: m.get_field_u8(3)),
            
            # Fault summary (0x105)
            'fault_voltage_warn': (lambda m: m.get_field_u8(0)),
            'fault_voltage_crit': (lambda m: m.get_field_u8(1)),
            'fault_temperature_warn': (lambda m: m.get_field_u8(2)),
            'fault_temperature_crit': (lambda m: m.get_field_u8(3)),
            'fault_current_warn': (lambda m: m.get_field_u8(4)),
            'fault_current_crit': (lambda m: m.get_field_u8(5)),
            'fault_range': (lambda m: m.get_field_u8(6)),
            'fault_external': (lambda m: m.get_field_u8(7)),
        }
        
        if field not in field_map:
            raise ValueError(f"Unknown field: {field}")
        
        return field_map[field](msg)


def create_test_suite() -> List[TestCase]:
    """Create all test cases from the test matrix."""
    tests = []
    
    # A.1: Normal heartbeat liveness
    tests.append(TestCase(
        'A.1', 'NS', 'Normal heartbeat liveness',
        [{'start_time_ms': 0, 'values': {
            'voltage': 12.0, 'temperature': 25.0, 'current': 0.0,
            'throttle': 0.0, 'brake': 0.0
        }}],
        5000,  # 5 seconds
        [
            {'msg_id': 0x100, 'field': 'alive', 'expected': 1, 'frame_range': (0, 100)},
            {'msg_id': 0x100, 'field': 'state_code', 'expected': 0, 'frame_range': (0, 100)},
        ]
    ))
    
    # A.2: State transition to warning
    tests.append(TestCase(
        'A.2', 'BC', 'State transition to warning',
        [
            {'start_time_ms': 0, 'values': {'voltage': 12.0}},
            {'start_time_ms': 1000, 'values': {'voltage': 10.8}},
            {'start_time_ms': 3000, 'values': {'voltage': 12.0}},
        ],
        5000,
        [
            {'msg_id': 0x100, 'field': 'state_code', 'expected': 0, 'frame_range': (0, 10)},
            {'msg_id': 0x100, 'field': 'state_code', 'expected': 1, 'frame_range': (10, 30)},
            {'msg_id': 0x100, 'field': 'state_code', 'expected': 0, 'frame_range': (30, 100)},
        ]
    ))
    
    # B.1: Normal voltage range
    tests.append(TestCase(
        'B.1', 'NS', 'Normal voltage range (12.0V)',
        [{'start_time_ms': 0, 'values': {'voltage': 12.0}}],
        2000,
        [
            {'msg_id': 0x101, 'field': 'voltage_v', 'expected': 12.0, 'frame_range': (0, 100)},
            {'msg_id': 0x101, 'field': 'voltage_warn', 'expected': 0, 'frame_range': (0, 100)},
            {'msg_id': 0x101, 'field': 'voltage_crit', 'expected': 0, 'frame_range': (0, 100)},
        ]
    ))
    
    # D.1: Throttle sweep 0–100%
    tests.append(TestCase(
        'D.1', 'NS', 'Throttle sweep 0–100%',
        [{'start_time_ms': t, 'values': {'throttle': (t / 2000) * 100}}
         for t in range(0, 2000, 100)],
        2000,
        [
            {'msg_id': 0x103, 'field': 'range_fault', 'expected': 0, 'frame_range': (0, 100)},
        ]
    ))
    
    # E.1: Current nominal zero
    tests.append(TestCase(
        'E.1', 'NS', 'Current nominal (0.0A)',
        [{'start_time_ms': 0, 'values': {'current': 0.0}}],
        2000,
        [
            {'msg_id': 0x104, 'field': 'current_a', 'expected': 0.0, 'frame_range': (0, 100)},
            {'msg_id': 0x104, 'field': 'current_warn', 'expected': 0, 'frame_range': (0, 100)},
            {'msg_id': 0x104, 'field': 'current_crit', 'expected': 0, 'frame_range': (0, 100)},
        ]
    ))
    
    # F.1: Fault summary all clear
    tests.append(TestCase(
        'F.1', 'NS', 'Fault summary all clear',
        [{'start_time_ms': 0, 'values': {
            'voltage': 12.0, 'temperature': 25.0, 'current': 0.0,
            'throttle': 0.0, 'brake': 0.0
        }}],
        2000,
        [
            {'msg_id': 0x105, 'field': 'fault_voltage_warn', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_voltage_crit', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_temperature_warn', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_temperature_crit', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_current_warn', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_current_crit', 'expected': 0},
            {'msg_id': 0x105, 'field': 'fault_range', 'expected': 0},
        ]
    ))
    
    return tests


def run_tests(test_filter: str = 'all', verbose: bool = False):
    """Run test suite and report results."""
    simulator = RaceCANSimulator()
    all_tests = create_test_suite()
    
    # Filter tests
    if test_filter != 'all':
        all_tests = [t for t in all_tests if t.test_id.startswith(test_filter)]
    
    print(f"RaceCAN Test Harness — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Running {len(all_tests)} test(s)\n")
    
    passed = 0
    failed = 0
    
    for test in all_tests:
        success = test.run(simulator, verbose)
        if success:
            passed += 1
            status = "PASS"
        else:
            failed += 1
            status = "FAIL"
        
        print(f"[{status}] {test.test_id}: {test.description}")
        if not verbose and test.errors:
            for error in test.errors[:3]:
                print(f"       {error}")
            if len(test.errors) > 3:
                print(f"       ... and {len(test.errors) - 3} more errors")
    
    print(f"\nSummary: {passed} passed, {failed} failed")
    return failed == 0


if __name__ == '__main__':
    test_filter = sys.argv[1] if len(sys.argv) > 1 else 'all'
    verbose = '--verbose' in sys.argv or '-v' in sys.argv
    
    success = run_tests(test_filter, verbose)
    sys.exit(0 if success else 1)
